### ISSUE TITLE
[BUG] Fail to build the project

### ISSUE THREAD

**Issue by starbops** [starbops/kubevirtbmc#10]
**Describe the bug**

When running `make`, it fails with the following message:

```shell
$ cd kubebmc/
$ make     
test -s /Users/starbops/Developer/Projects/ZPCC/kubebmc-main/bin/controller-gen && /Users/starbops/Developer/Projects/ZPCC/kubebmc-main/bin/controller-gen --version | grep -q v0.13.0 || \
        GOBIN=/Users/starbops/Developer/Projects/ZPCC/kubebmc-main/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0
/Users/starbops/Developer/Projects/ZPCC/kubebmc-main/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102c95004]

goroutine 76 [running]:
go/types.(*Checker).handleBailout(0x140001ca200, 0x14000eebd18)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/check.go:367 +0x9c
panic({0x102f6da60?, 0x103508af0?})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x1030389b0, 0x103511320})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x1030389b0?, 0x103511320?})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x10303ec50, 0x1034dc240}, 0x140001ca200, 0x103511320, 0x14000eeb468)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x140001ca200, 0x14000eca080, 0x103511320)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x140001ca200, 0x14000eca080, {0x1030389d8, 0x140001e0ee0})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/expr.go:375 +0x304
go/types.(*Checker).assignment(0x140001ca200, 0x14000eca080, {0x1030389d8, 0x140001e0ee0}, {0x102dacce2, 0x14})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/assignments.go:52 +0x23c
go/types.(*Checker).initConst(0x140001ca200, 0x14000ea6300, 0x14000eca080)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/assignments.go:126 +0x274
go/types.(*Checker).constDecl(0x140001ca200, 0x14000ea6300, {0x10303b558, 0x1400115e760}, {0x10303b558, 0x1400115e780}, 0x0)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/decl.go:490 +0x250
go/types.(*Checker).objDecl(0x140001ca200, {0x103043d40, 0x14000ea6300}, 0x0)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/decl.go:191 +0x84c
go/types.(*Checker).packageObjects(0x140001ca200)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/resolver.go:693 +0x468
go/types.(*Checker).checkFiles(0x140001ca200, {0x14000ed8780, 0x5, 0x5})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0x14000221470, 0x1400024fc20)
        /Users/starbops/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/loader.go:286 +0x2d8
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0x1400024fc20)
        /Users/starbops/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/loader.go:99 +0x44
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0x14000e05ec0, 0x1400024fc20)
        /Users/starbops/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/refs.go:268 +0x304
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x51?)
        /Users/starbops/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/refs.go:262 +0x58
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 54
        /Users/starbops/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/refs.go:260 +0x230
make: *** [manifests] Error 2
```

**To Reproduce**

1. Clone the project
2. Run `make` and should see the error

**Expected behavior**

The project should be able to be built.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] macOS 14.5
 - Version [e.g. 22] trying to build from the main branch

**Additional context**

It seems to be related to kubernetes-sigs/controller-tools#880.

**Comment by starbops** [comment]
Close as resolved by #11
