### ISSUE TITLE
[BUG] Agent crashes when communicating to the Redfish session service

### ISSUE THREAD

**Issue by starbops** [starbops/kubevirtbmc#41]
**Describe the bug**

It's possible (with a small chance) that the agent gets panic at runtime:

```
2024/12/18 15:46:38 GET /redfish/v1/ RedfishV1Get_0 75.647µs
2024/12/18 15:46:38 GET /redfish/v1/ RedfishV1Get_0 51.723µs
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 304 [running]:
kubevirt.io/kubevirtbmc/pkg/session.AddToken(...)
    /workspace/pkg/session/token.go:37
kubevirt.io/kubevirtbmc/pkg/redfish.(*handler).Authenticate(0x8?, 0xc004f04160, 0xc004e63f80?)
    /workspace/pkg/redfish/handler.go:35 +0x15a
kubevirt.io/kubevirtbmc/pkg/redfish.(*APIService).RedfishV1SessionServiceSessionsPost(_, {_, _}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
    /workspace/pkg/redfish/api_service.go:53813 +0x70
kubevirt.io/kubevirtbmc/pkg/generated/redfish/server.(*DefaultAPIController).RedfishV1SessionServiceSessionsPost(0xc000010fc0, {0x1a934c0, 0xc00038a1c0}, 0xc0043a0f00)
    /workspace/pkg/generated/redfish/server/api_default.go:119795 +0x23c
net/http.HandlerFunc.ServeHTTP(0xc00438cd80?, {0x1a934c0?, 0xc00038a1c0?}, 0xc00438cd80?)
    /usr/local/go/src/net/http/server.go:2220 +0x29
kubevirt.io/kubevirtbmc/pkg/generated/redfish/server.NewRouter.Logger.func1({0x1a934c0, 0xc00038a1c0}, 0xc0043a0f00)
    /workspace/pkg/generated/redfish/server/logger.go:23 +0x95
net/http.HandlerFunc.ServeHTTP(0xc0043a0dc0?, {0x1a934c0?, 0xc00038a1c0?}, 0x10?)
    /usr/local/go/src/net/http/server.go:2220 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000300, {0x1a934c0, 0xc00038a1c0}, 0xc0043a08c0)
    /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1e2
net/http.serverHandler.ServeHTTP({0x1a8f1f8?}, {0x1a934c0?, 0xc00038a1c0?}, 0x6?)
    /usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc004eb62d0, {0x1a97100, 0xc004ec0b70})
net/http.(*connReader).Read(0xc004ec0240, {0xc0001d9000, 0x1000, 0x1000})
    /usr/local/go/src/net/http/server.go:798 +0x14b
bufio.(*Reader).fill(0xc0021e4060)
    /usr/local/go/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc0021e4060, 0x4)
    /usr/local/go/src/bufio/bufio.go:148 +0x53
net/http.(*conn).serve(0xc004d4a120, {0x1a97100, 0xc004ec0b70})
    /usr/local/go/src/net/http/server.go:2127 +0x738
created by net/http.(*Server).Serve in goroutine 55
    /usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 239 [IO wait]:
internal/poll.runtime_pollWait(0x7f374cb0abc0, 0x72)
    /usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc004c6e080?, 0xc0003da000?, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc004c6e080, {0xc0003da000, 0x1000, 0x1000})
    /usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
net.(*netFD).Read(0xc004c6e080, {0xc0003da000?, 0xc002209aa0?, 0x4edde5?})
    /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00033a020, {0xc0003da000?, 0x0?, 0xc004cb0248?})
    /usr/local/go/src/net/net.go:189 +0x45
net/http.(*connReader).Read(0xc004cb0240, {0xc0003da000, 0x1000, 0x1000})
    /usr/local/go/src/net/http/server.go:798 +0x14b
bufio.(*Reader).fill(0xc004f06180)
    /usr/local/go/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc004f06180, 0x4)
    /usr/local/go/src/bufio/bufio.go:148 +0x53
net/http.(*conn).serve(0xc004d4a1b0, {0x1a97100, 0xc004ec0b70})
    /usr/local/go/src/net/http/server.go:2127 +0x738
created by net/http.(*Server).Serve in goroutine 55
    /usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 302 [IO wait]:
internal/poll.runtime_pollWait(0x7f374cb0add0, 0x72)
    /usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc004d36080?, 0xc000388000?, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc004d36080, {0xc000388000, 0x1000, 0x1000})
    /usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
net.(*netFD).Read(0xc004d36080, {0xc000388000?, 0xc002203aa0?, 0x4edde5?})
    /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0006a4010, {0xc000388000?, 0x0?, 0xc00438c278?})
    /usr/local/go/src/net/net.go:189 +0x45
net/http.(*connReader).Read(0xc00438c270, {0xc000388000, 0x1000, 0x1000})
    /usr/local/go/src/net/http/server.go:798 +0x14b
bufio.(*Reader).fill(0xc00031aba0)
    /usr/local/go/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc00031aba0, 0x4)
    /usr/local/go/src/bufio/bufio.go:148 +0x53
net/http.(*conn).serve(0xc004eb6090, {0x1a97100, 0xc004ec0b70})
    /usr/local/go/src/net/http/server.go:2127 +0x738
created by net/http.(*Server).Serve in goroutine 55
    /usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 369 [IO wait]:
internal/poll.runtime_pollWait(0x7f374cb0b508, 0x72)
    /usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc004d36100?, 0xc00438ca01?, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc004d36100, {0xc00438ca01, 0x1, 0x1})
    /usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
net.(*netFD).Read(0xc004d36100, {0xc00438ca01?, 0xc004916748?, 0x470a10?})
    /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0006a4018, {0xc00438ca01?, 0xc0049167d0?, 0x25b4240?})
    /usr/local/go/src/net/net.go:189 +0x45
net/http.(*connReader).backgroundRead(0xc00438c9f0)
    /usr/local/go/src/net/http/server.go:690 +0x37
created by net/http.(*connReader).startBackgroundRead in goroutine 304
    /usr/local/go/src/net/http/server.go:686 +0xb6

goroutine 353 [running]:
kubevirt.io/kubevirtbmc/pkg/session.AddToken(...)
    /workspace/pkg/session/token.go:37
kubevirt.io/kubevirtbmc/pkg/redfish.(*handler).Authenticate(0x8?, 0xc0040b40f0, 0xc004e2df80?)
    /workspace/pkg/redfish/handler.go:35 +0x15a
kubevirt.io/kubevirtbmc/pkg/redfish.(*APIService).RedfishV1SessionServiceSessionsPost(_, {_, _}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
    /workspace/pkg/redfish/api_service.go:53813 +0x70
kubevirt.io/kubevirtbmc/pkg/generated/redfish/server.(*DefaultAPIController).RedfishV1SessionServiceSessionsPost(0xc000010fc0, {0x1a934c0, 0xc0005b62a0}, 0xc00432a3c0)
    /workspace/pkg/generated/redfish/server/api_default.go:119795 +0x23c
net/http.HandlerFunc.ServeHTTP(0xc004f02360?, {0x1a934c0?, 0xc0005b62a0?}, 0xc004f02360?)
    /usr/local/go/src/net/http/server.go:2220 +0x29
kubevirt.io/kubevirtbmc/pkg/generated/redfish/server.NewRouter.Logger.func1({0x1a934c0, 0xc0005b62a0}, 0xc00432a3c0)
    /workspace/pkg/generated/redfish/server/logger.go:23 +0x95
net/http.HandlerFunc.ServeHTTP(0xc00432a140?, {0x1a934c0?, 0xc0005b62a0?}, 0x10?)
    /usr/local/go/src/net/http/server.go:2220 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000300, {0x1a934c0, 0xc0005b62a0}, 0xc002f5b680)
    /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1e2
net/http.serverHandler.ServeHTTP({0x1a8f1f8?}, {0x1a934c0?, 0xc0005b62a0?}, 0x6?)
    /usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc004c4c120, {0x1a97100, 0xc004ec0b70})
    /usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 55
    /usr/local/go/src/net/http/server.go:3360 +0x485
```

The internal map - `tokenStore` - should be concurrent-safe. This could be done by a read-write lock to protect the map.

**To Reproduce**

I believe it's hard to reproduce by curling the API manually.

**Expected behavior**

The agent should not panic.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Harvester v1.4.0 (based on SLE Micro 5.5)
 - KubeVirtBMC version: v0.4.0

**Additional context**

I observed the error during the Harvester provisioning using Seeder. It could also happen to Tinkerbell, too.

**Comment by starbops** [comment]
Verified that the issue has been fixed.
